apiVersion: v1
kind: Template
labels:
  template: graph-sync-cronjob
  thoth: 0.1.0
metadata:
  name: graph-sync-cronjob
  annotations:
    description: This is Thoth Core - Graph Sync Job
    openshift.io/display-name: "Thoth: Graph Sync Job"
    version: 0.3.0
    tags: poc,thoth,ai-stacks,graph-sync-job
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Graph Sync Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: graph-sync
    labels:
      app: thoth-core
  spec:
    schedule: "@daily"
    suspend: true
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - image: graph-sync-job
              name: graph-sync
              env:
              - name: THOTH_DEPLOYMENT_NAME
                valueFrom:
                  configMapKeyRef:
                    key: storage-bucket-name
                    name: thoth
              - name: THOTH_JANUSGRAPH_HOST
                value: janusgraph
              - name: THOTH_JANUSGRAPH_PORT
                value: '80'
              - name: THOTH_SYNC_OBSERVATIONS
                valueFrom:
                  configMapKeyRef:
                    key: sync-observations
                    name: thoth
              - name: THOTH_S3_ENDPOINT_URL
                valueFrom:
                  configMapKeyRef:
                    key: ceph-host
                    name: thoth
              - name: THOTH_CEPH_BUCKET
                valueFrom:
                  configMapKeyRef:
                    key: ceph-bucket-name
                    name: thoth
              - name: THOTH_CEPH_BUCKET_PREFIX
                valueFrom:
                  configMapKeyRef:
                    key: ceph-bucket-prefix
                    name: thoth
              - name: THOTH_CEPH_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: thoth
                    key: ceph-key-id
              - name: THOTH_CEPH_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: thoth
                    key: ceph-secret-key
              - name: RSYSLOG_HOST
                valueFrom:
                 configMapKeyRef:
                   key: rsyslog-host
                   name: thoth
              - name: RSYSLOG_PORT
                valueFrom:
                 configMapKeyRef:
                   key: rsyslog-port
                   name: thoth
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
            restartPolicy: Never
