apiVersion: v1
kind: Template
metadata:
  name: graph-sync-job-provenance-checker
  annotations:
    description: "Thoth: Graph Sync Job for provenance-checker documents"
    openshift.io/display-name: "Thoth: Graph Sync Job Provenance Checker"
    version: 0.6.1
    tags: thoth,ai-stacks,aistacks,graph-sync-job
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth's Graph Sync Job for Provenance Checkers on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: graph-sync-job-provenance-checker
    app: thoth
    component: graph-sync
    graph-sync-type: provenance-checker

parameters:
  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - description: Namespace the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "thoth-infra-stage"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - name: THOTH_SYNC_DOCUMENT_ID
    required: true
    description: Document id to be synced.

  - name: THOTH_JOB_ID
    required: true
    description: Graph sync job identifier.

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${THOTH_JOB_ID}"
      labels:
        app: thoth
        component: graph-sync
        graph-sync-document-id: "${THOTH_SYNC_DOCUMENT_ID}"
        graph-sync-type: provenance-checker
        # Clean this up after one hour.
        mark: cleanup
        ttl: "1h"
    spec:
      backoffLimit: 10
      template:
        metadata:
          labels:
            app: thoth
            component: graph-sync
            mark: cleanup
            ttl: "1h"
        spec:
          containers:
            - name: graph-sync
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/graph-sync-job:${IMAGE_STREAM_TAG}"
              env:
                - name: THOTH_ONLY_PROVENANCE_CHECKER_DOCUMENTS
                  value: "1"
                - name: THOTH_SYNC_DOCUMENT_ID
                  value: "${THOTH_SYNC_DOCUMENT_ID}"
                - name: THOTH_FORCE_SYNC
                  value: "1"
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: THOTH_S3_ENDPOINT_URL
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-host
                      name: thoth
                - name: THOTH_CEPH_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-name
                      name: thoth
                - name: THOTH_CEPH_BUCKET_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-prefix
                      name: thoth
                - name: THOTH_CEPH_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-key-id
                - name: THOTH_CEPH_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-secret-key
                - name: THOTH_METRICS_PUSHGATEWAY_URL
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: metrics-pushgateway-url
                - name: "THOTH_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
                - name: GRAPH_SERVICE_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: graph-service-host
                      name: thoth
                - name: GRAPH_TLS_PATH
                  value: "/var/run/secrets/dgraph"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
              volumeMounts:
                - mountPath: /var/run/secrets/dgraph
                  name: dgraph-tls-secrets
                  readOnly: true
          volumes:
            - name: dgraph-tls-secrets
              secret:
                defaultMode: 420
                secretName: dgraph-tls
          restartPolicy: OnFailure
